template: "Hello World"
server:
  type: default
  adminContextPath: /admin
  applicationContextPath: /
  applicationConnectors:
    - type: http
      port: 4000
  adminConnectors:
    - type: http
      port: 4010
